- name: installing cart component
  hosts: cart
  become: yes
  tasks:
    - name: disable default nodejs
      ansible.builtin.command: dnf module disable nodejs -y

    - name: enable default nodejs:20
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present 

    - name: create roboshop system user
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        system: true
        home: /app

    - name: create app directory
      ansible.builtin.file:
        path: /app #which path to create
        state: directory #directory ni create chestundi

    - name: download cart code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
        dest: /tmp/cart.zip

#this module by default thinks, file exists on ansible control server, need to extract on to remote machine
#emote_src means file already exists in catalogue server
    - name: extract cart code
      ansible.builtin.unarchive:
        src: /tmp/cart.zip
        dest: /app
        remote_src: yes

    - name: install dependencies
      community.general.npm:
        path: /app

    - name: copy cart service to system directory
      ansible.builtin.copy:
        src: cart.service
        dest: /etc/systemd/system/cart.service

    - name: daemon reload
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: start and enable cart
      ansible.builtin.service:
        name: cart
        state: started
        enabled: yes
